# Generated by Django 4.1.7 on 2023-03-11 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scheme', max_length=30, unique=True)),
                ('name1', models.CharField(blank=True, default='Column', max_length=30)),
                ('name2', models.CharField(blank=True, default='Column', max_length=30)),
                ('name3', models.CharField(blank=True, default='Column', max_length=30)),
                ('name4', models.CharField(blank=True, default='Column', max_length=30)),
                ('name5', models.CharField(blank=True, default='Column', max_length=30)),
                ('name6', models.CharField(blank=True, default='Column', max_length=30)),
                ('type1', models.CharField(choices=[('0', 'Choose..'), ('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], default='0', max_length=30)),
                ('type2', models.CharField(choices=[('0', 'Choose..'), ('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], default='0', max_length=30)),
                ('type3', models.CharField(choices=[('0', 'Choose..'), ('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], default='0', max_length=30)),
                ('type4', models.CharField(choices=[('0', 'Choose..'), ('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], default='0', max_length=30)),
                ('type5', models.CharField(choices=[('0', 'Choose..'), ('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], default='0', max_length=30)),
                ('type6', models.CharField(choices=[('0', 'Choose..'), ('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], default='0', max_length=30)),
                ('order1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('order2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('order3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('order4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('order5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('order6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheme.scheme')),
            ],
        ),
    ]
