# Generated by Django 4.1.7 on 2023-03-08 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(default='None', max_length=30)),
                ('name1', models.CharField(blank=True, default='None', max_length=30)),
                ('name2', models.CharField(blank=True, default='None', max_length=30)),
                ('name3', models.CharField(blank=True, default='None', max_length=30)),
                ('name4', models.CharField(blank=True, default='None', max_length=30)),
                ('name5', models.CharField(blank=True, default='None', max_length=30)),
                ('name6', models.CharField(blank=True, default='None', max_length=30)),
                ('type1', models.CharField(choices=[('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], max_length=30)),
                ('type2', models.CharField(choices=[('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], max_length=30)),
                ('type3', models.CharField(choices=[('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], max_length=30)),
                ('type4', models.CharField(choices=[('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], max_length=30)),
                ('type5', models.CharField(choices=[('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], max_length=30)),
                ('type6', models.CharField(choices=[('1', 'Full Name'), ('2', 'Job'), ('3', 'Company'), ('4', 'Integer'), ('5', 'Text'), ('6', 'Email')], max_length=30)),
                ('order1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('order2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('order3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('order4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('order5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('order6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
